default:
  ALLOWED_HOSTS:
  - '*'
  INSTALLED_APPS:
  - django.contrib.admin
  - django.contrib.auth
  - django.contrib.contenttypes
  - django.contrib.sessions
  - django.contrib.messages
  - django.contrib.staticfiles
  - rest_framework
  - corsheaders
  - trees
  DATABASES:
    default:
      ENGINE: 'django.db.backends.postgresql'
      USER: admin
      NAME: ysdb
      PORT: 5432
      TEST:
        NAME: testing
  CHAR_FIELD_MAX_LENGTH: 100
  REST_FRAMEWORK:
    DEFAULT_AUTHENTICATION_CLASSES:
    - 'rest_framework.authentication.SessionAuthentication'
    - 'rest_framework.authentication.BasicAuthentication'
development:
  DEBUG: True
  CORS_ALLOWED_ORIGINS:
  - http://localhost:3000
  CORS_ALLOW_CREDENTIALS: True
  CSRF_TRUSTED_ORIGINS:
  - http://localhost:3000
  CSRF_COOKIE_NAME: 'csrftoken'
  CSRF_COOKIE_HTTPONLY: False
