# Generated by Django 5.0.6 on 2024-06-29 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_remove_profile_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantedtree',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.account'),
        ),
    ]
