# Generated by Django 5.0.6 on 2024-06-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_profile_tree_plantedtree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantedtree',
            name='age',
        ),
        migrations.AddField(
            model_name='plantedtree',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='plantedtree',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='accounts',
            field=models.ManyToManyField(related_name='users', to='trees.account'),
        ),
    ]
